[package]
name = "half_duplex_wire"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
embedded-hal = {version = "^0.2.3", features = ["unproven"]}
